### ISSUE TITLE
Support [u8] input?

### ISSUE THREAD

**Issue by kornelski** [magiclen/html-minifier#5]
I'm using a template engine that writes to `Vec<u8>`, and not `String`. I'd like to minify that output without unnecessary conversion and UTF-8 check.

`digest` already works on bytes. Could you add a method to digest bytes?

**Comment by magiclen** [comment]
You can use the `core::str::from_utf8_unchecked` function to convert `&[u8]` to `&str` without UTF-8 check.

**Comment by kornelski** [comment]
That's what I've done for now, but I'd like to avoid unnecessary unsafe code.

**Comment by magiclen** [comment]
If `HTMLMinifier` added a `digest_u8_slice` method, that should also be marked as an unsafe function.

**Comment by kornelski** [comment]
Perhaps coupled with io::Write output it could be safe? (bytes in, bytes out)

**Comment by magiclen** [comment]
Inputing a `&[u8]` is unsafe, which is because the current algorithm doesn't check UTF-8.

I think the `io::Read` trait can be implemented for `HTMLMinifier`. In the `read` method, check UTF-8 first and then use the `digest` method. The `digest`method should be separated into smaller methods by the width of UTF-8 characters to avoid getting width repeatedly if inputing data from the `read` method.

**Comment by kornelski** [comment]
I mean `get_html` returns `&str`, so that requires input to be valid UTF-8. However, if that method didn't exist, then AFAIK it wouldn't matter if the input was valid UTF-8. `io::Write` takes `[u8]`, so it's not concerned with UTF-8 validity. 

In terms of implementation, you could make a lower-level `HTMLMinifier` that operates on `[u8]` input and writes to `io::Write`, and then wrap it in higher level `HTMLMinifier` that feeds it `str.as_bytes()` and gives it `Vec<u8>` to write into, which it would be able to cast to str if it knew input was valid UTF-8.

**Comment by magiclen** [comment]
The minification is based on UTF-8-encoded HTML. That is why UTF-8 validation for the input text is necessary no matter whether the `get_html` method or `io::Write` exists.

**Comment by kornelski** [comment]
Oh, I see in the implementation that you're checking the UTF-8 width. I've assumed that since it starts with `as_bytes()` it's going to pay attention only to the ASCII subset and skip over everything else.

**Comment by magiclen** [comment]
You inspired me to add a new option to disable the **one line** minification. When it is disabled, in HTML text (not in tags), `HTMLMinifier` just remains the first whitespace in a succession of consecutive whitespaces, but if `\n` is in the consecutive whitespaces, then `\n` is remained instead. With this, the CJ characters have no need to be checked, neither does the width.

This could also improve the performance and might be able to ignore the UTF-8 encoding (not sure if all encodings are self-synchronizing and support the ASCII subset).

**Comment by kornelski** [comment]
Nice. All 8-bit encodings allowed in HTML must be ASCII superset, because it needs to find meta tag with the encoding name. 
Byte-per-char code pages are definitely safe. 

Shift-jis and Big5 are ascii superset, but have two byte sequences where the second byte can be an ASCII letter. It can t be `<>"` though. 

EUC and GB2312 encodings use high bytes only for multibyte sequences.
