### ISSUE TITLE
Inline SVG is malformed

### ISSUE THREAD

**Issue by kornelski** [magiclen/html-minifier#6]
`<svg>` element in HTML uses XML-ish syntax where `/>` is meaningful.

`<line/><line/>` gets minified to `<line><line>`, which breaks rendering.

**Comment by magiclen** [comment]
That seems to be a bug because `<line/><line/>` should never be minified to `<line><line>`.

Could you provide a case to reproduce this malformed behavior?

**Comment by kornelski** [comment]
The charts on https://lib.rs/crates/bytes got malformed. After minification they render only one line, instead of all of them.

**Comment by magiclen** [comment]
I couldn't reproduce that. I minified the whole page and everything still worked.

**Comment by kornelski** [comment]
`<line stroke-opacity=0.3 />` is changed to `<line stroke-opacity=0.3/>` which changes value of the attribute to "0.3/" instead of closing the element.

**Comment by magiclen** [comment]
It has been fixed since `2.0.10`.

**Comment by kornelski** [comment]
Works fine now. Thank you!
